### ISSUE TITLE
How can I get online guest count ?

### ISSUE THREAD

**Issue by codes-zain** [shetabit/visitor#14]
Hi 
Is it possible to get online visitor or guest users that are not login  in ?
if is possible how can I do that

**Comment by WebLab-ImpCode** [comment]
+1

**Comment by WebLab-ImpCode** [comment]
+1
I looked at the source code of the package and came to the conclusion that there is currently no available method that could get the number of guests. 
It's strange enough why an additional table is needed if it is enough to update the date field in the users table.
So I'm surprised the package does not provide this functionality, or am I wrong?

Since guests are also logged into the _visits_ table, then I see only one way, this is to create my query to the _visits_ table.
```php
DB::table('visits')->select('id')
        ->where('created_at', '>=', \Carbon\Carbon::now()->subMinutes(3))
        ->whereNull('visitor_id')
        ->groupBy('ip')
        ->get()
        ->count();
```
The code is rough, given as an example

**Comment by khanzadimahdi** [comment]
you can add this feature and send pull request.

**Comment by CodeNinjaUG** [comment]
hey did u work on the guest visitors problem

**Comment by khanzadimahdi** [comment]
please add this feature to the package and send a pull request. I will merge it.
